### ISSUE TITLE
Android Build Not Working

### ISSUE THREAD

**Issue by hrastnik** [Beaconstac/react-native-nearbee#1]
I've built the sample app for Android, but it's stuck in "Looking for nearby beacons" screen with a spinner.

I've placed the beacon right next to the phone, but nothing shows up in the app.

**Comment by k1slay** [comment]
Hi,
Can you please share the Organization ID that you are using for the build. Also, can you share the logs that you get from the SDK. You can find the logs by filtering on `Nearbee` string in Android studio

**Comment by hrastnik** [comment]
My organization ID is 4281

I'll check the logs and get back to you

**Comment by hrastnik** [comment]
My organization ID is 4281

I'll check the logs and get back to you

**Comment by hrastnik** [comment]
The only logs I get from Nearbee are:

```
04-12 09:17:41.781 2411-2458/? D/RNNearbee: Init
04-12 09:17:45.000 2411-2458/com.sample_app D/RNNearbee: Started scanning
```

**Comment by hrastnik** [comment]
However, I do get these logs repeating indefinitely:

```
04-12 09:20:36.924 3379-3379/com.sample_app V/Beaconstac: Started scanning
04-12 09:20:39.924 3379-3379/com.sample_app V/Beaconstac: Stopped scanning
04-12 09:20:41.940 3379-3379/com.sample_app V/Beaconstac: Started scanning
04-12 09:20:49.949 3379-3379/com.sample_app V/Beaconstac: Stopped scanning
... // This repeats in every ~2 seconds
```

**Comment by sachinmobstac** [comment]
@hrastnik, Closing this issue as you need a minimum **Premium** subscription.
