### ISSUE TITLE
Unable To Build For iOS - "pod install" Failing

### ISSUE THREAD

**Issue by hrastnik** [Beaconstac/react-native-nearbee#2]
When running react-native run-ios for the sample app, I get an error saying I should run pod install.
When pod install is ran, it throws the following error

NoMethodError - undefined method `basename' for #<String:0x00007fd7d32f97b8>
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:723:in `rescue in _eval_podspec'
....

Not sure if it's relevant, but this message appears along with the error...

Looking for related issues on cocoapods/cocoapods...
 - Update camelCase to snake case in all specs before the next release.
   https://github.com/CocoaPods/CocoaPods/issues/152 [closed] [18 comments]
   27 Apr 2012

**Comment by sachinmobstac** [comment]
Hi @hrastnik, Can you please update the CocoaPods to 1.6.1 the latest one and run the project. The project uses a Swift Static Library which is supported in the CocoaPods from 1.6.0.

**Comment by hrastnik** [comment]
I tried it, but it still throws the same error. Any other ideas?

**Comment by sachinmobstac** [comment]
@hrastnik, I have fixed those issues. Can you redownload/clone the repo and follow the below steps:

1. Move to sample_app folder
2. Run `npm install`
3. Move to ios
4. Run `pod install`

**Comment by hrastnik** [comment]
I can confirm the issue is fixed now. Running `pod install` now runs without errors.

However, once I run the app I still can't locate the beacons. It's still stuck in the screen saying "Looking for nearby beacons"

Can you confirm the sample app can successfully locate any beacons?

**Comment by sachinmobstac** [comment]
@hrastnik, We are not handling the Bluetooth connections gracefully in the sample_app. Please enable the Bluetooth on your device before running the Xcode project. 

There was a bug with the device permission checking react native package, I have updated the package. Please redownload/clone.

**Note:** you have to run the project on a physical device as the Simulator doesn't allow Bluetooth connections.

**Comment by hrastnik** [comment]
I cloned the latest git repo.
I turned on Bluetooth on the device (iPhone 8)
I changed the co.nearbee.api_key key in Info.plist to my api key
I changed the co.nearbee.organization_id key in Info.plist to my organization ID
I built and ran the app on the device.
I made sure the beacon is turned on and placed it next to my device.

Nothing happens.

Can you confirm you have tried the process on your side and you can successfully register the beacon on the device?

**Comment by sachinmobstac** [comment]
@hrastnik, I tried the following and below is the result.
![File](https://user-images.githubusercontent.com/34122260/56036293-24ed3800-5d4a-11e9-84dd-22938da350e3.jpg)

**Comment by sachinmobstac** [comment]
@hrastnik, Can you let me know the serial number of the beacon which you are using?

**Comment by hrastnik** [comment]
I've tried these beacons

AC233F251432
AC233F251431
AC233F2513B1

**Comment by hrastnik** [comment]
I get the following errors in the XCode output

```
Error Domain=co.nearbee.sdk Code=-3 "Server returned error <NSHTTPURLResponse: 0x2834c58a0> { URL: https://nearbee.beaconstac.com/auth } 
{ 
  Status Code: 403, Headers {
    "Content-Length" =     (
        60
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Fri, 12 Apr 2019 13:53:44 GMT"
    );
    Etag =     (
        "W/\"3c-4pItPkdJpboFo7LZJIePQXoAg4E\""
    );
    Server =     (
        "nginx/1.15.8"
    );
    Via =     (
        "1.1 google"
    );
    "alt-svc" =     (
        clear
    );
    "x-powered-by" =     (
        Express
    );
} }"
```

**Comment by hrastnik** [comment]
@sachinmobstac Do I have to have a Premium account to be able to use the library?

**Comment by sachinmobstac** [comment]
@hrastnik, Yes [here](https://www.beaconstac.com/buy-beacons/) is our subscription plans

**Comment by sachinmobstac** [comment]
@hrastnik, Closing this issue as you need a minimum **Premium** subscription.

**Comment by hrastnik** [comment]
Yes, that was the issue. However I think the sample app still has a bug. The import still expects 'react-native-permissions' while the package name is 'react-native-permissions-ble-fix'.

You should update the sample app import

**Comment by sachinmobstac** [comment]
@hrastnik, Thanks I have updated.
