### ISSUE TITLE
pod install fail on IOS

### ISSUE THREAD

**Issue by knawaz771** [Beaconstac/react-native-nearbee#6]
Hello, I am trying to run `pod install` but i am getting following error

`[!] CocoaPods could not find compatible versions for pod "RNNearBee":`
 ` In Podfile:`
 `   RNNearBee (from ../node_modules/react-native-nearbee)`

`Specs satisfying the RNNearBee (from ../node_modules/react-native-nearbee) dependency were found, but they required a higher minimum deployment target.`

I am on `React Native 0.61.4`, tested on `0.60` as well, My cocoapods version is `1.8` and my Xcode `version is 11.2`

please help. Thanks

**Comment by shashankraj0202** [comment]
We have not released support for Xcode 11. Please try building using Xcode 10.x

**Comment by knawaz771** [comment]
> We have not released support for Xcode 11 yet. Please try building using Xcode 10.x

thanks for your reply. I tried this with `Xcode 10.1` , `react native 0.60.4` but I still get the same error mentioned in question. I really need this to work :-(

**Comment by shashankraj0202** [comment]
Please try running the sample app provided in this project? If you are able to run it, please try building with react-native@0.59.10.

React Native 0.60.x has some breaking changes and is causing build fails.

If you need to use react native 0.60.x you can use the NearBee pod(0.2.1) directly in you IOS project and `co.nearbee:nearbeesdk:0.2.1` for Android in your project.

**Comment by shashankraj0202** [comment]
Can you please share your Podfile as well?

**Comment by knawaz771** [comment]
what do you mean by `use the NearBee pod(0.2.1)  directly in your IOS project` ??

Below are contents of Podfile in ios directory

`platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target '[project-name]' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'react-native-location', :path => '../node_modules/react-native-location/react-native-location.podspec'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  # pod 'RNImgToBase64', :path => '../node_modules/react-native-image-base64'


  target 'project-name' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'project-name-tvOS' do
  # Pods for MassyStores-tvOS

  target 'project-name-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end`

**Comment by shashankraj0202** [comment]
NearBee can be built only for targets ios, '10.0'. Please update your pod file.

I tried building it with react-native .60.* and seems like there are some issues while building. We will get it fixed ASAP.

Meanwhile can you please use react-native 0.59.10.

**Comment by tiagocharo** [comment]
I get the same errors on IOS, even making the adjustments indicated in the comments above, could you provide a react-native-nearbee project running on IOS and Android?

**Comment by shashankraj0202** [comment]
There is a sample app provided in this repository. You can clone this repository and try running the sample app provided.

Please check https://github.com/Beaconstac/react-native-nearbee/tree/master/sample_app

**Comment by knawaz771** [comment]
@shashankraj0202 can I have an update on this ? this package seems only compatible with `react-native` version 0.59 or below. with the release of 0.60 the linking is not happening the way it was in RN0.59 or below versions.

Now RN version 0.61+ is available. this is a paid package, you should have fixed it by now for RN0.60+

Please advice when we should expect it Or we should simply tell our clients that this is not going to work as team on your side is busy trying to fix it. It's a PAID service as you know. Thanks

**Comment by ravipratapm** [comment]
> @shashankraj0202 can I have an update on this ? this package seems only compatible with `react-native` version 0.59 or below. with the release of 0.60 the linking is not happening the way it was in RN0.59 or below versions.
> 
> Now RN version 0.61+ is available. this is a paid package, you should have fixed it by now for RN0.60+
> 
> Please advice when we should expect it Or we should simply tell our clients that this is not going to work as team on your side is busy trying to fix it. It's a PAID service as you know. Thanks

Hi, can you please tell us your Beaconstac account Organization ID? You'll find it on the Account page.

We are checking if we can support RN0.61.

**Comment by mattyglover** [comment]
Has support for RN0.6x been sorted out?

**Comment by ravipratapm** [comment]
Not yet, I'm afraid.

**Comment by Souro7** [comment]
@mattyglover We have released support for react native 0.60.6 in the latest release (v3.0.0)

**Comment by Souro7** [comment]
Support for RN0.60.6 is released. Closing this issue.
