### ISSUE TITLE
Could not find co.nearbee:nearbeebasesdk:0.2.1.

### ISSUE THREAD

**Issue by ansari-aamir** [Beaconstac/react-native-nearbee#7]
Getting error while building android app, seems like url for sdk not wroking.
  https://dl.google.com/dl/android/maven2/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.pom
      https://dl.google.com/dl/android/maven2/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.jar
      https://jcenter.bintray.com/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.pom
      https://jcenter.bintray.com/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.jar
   https://maven.google.com/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.pom
      https://maven.google.com/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.jar
      https://jitpack.io/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.pom
      https://jitpack.io/co/nearbee/nearbeebasesdk/0.2.1/nearbeebasesdk-0.2.1.jar

**Comment by shashankraj0202** [comment]
Please see https://github.com/Beaconstac/react-native-nearbee#pre-requisites.

Add mobstac maven dependency to your gradle.

```allprojects {
    repositories {
        …
        maven {
            url  "https://dl.bintray.com/mobstac/maven"
        }
        …
    }
}```
